base16:
    filename: include/{{ scheme-system }}-{{ scheme-slug }}.h

base24:
    filename: include/{{ scheme-system }}-{{ scheme-slug }}.h
    supported-systems: [base24]

list:
    filename: include/tinted.h
    supported-systems: [list]
