#!/bin/sh
#
# build-aggregate.sh: Generates include/base16.h, the aggregate header that
# exposes every scheme header behind opt-in preprocessor guards.
#
# Usage: scripts/build-aggregate.sh
#
# Run this after regenerating the scheme headers with:
#   tinted-builder-rust build .

set -eu

LC_ALL=C
export LC_ALL

# Always operate from the repository root.
cd "$(dirname "$0")/.."

out="include/base16.h"
tmp="$out.tmp"

# Uppercase a scheme slug and replace dashes with underscores.
# e.g. "atelier-cave-light" -> "ATELIER_CAVE_LIGHT"
macro_slug() {
    printf '%s' "$1" | tr 'a-z-' 'A-Z_'
}

# Replace dashes with underscores, keeping case.
# e.g. "atelier-cave-light" -> "atelier_cave_light"
symbol_slug() {
    printf '%s' "$1" | tr -- '-' '_'
}

base16_slugs=$(ls include/base16-*.h | sed -e 's|^include/base16-||' -e 's|\.h$||' | sort)
base24_slugs=$(ls include/base24-*.h | sed -e 's|^include/base24-||' -e 's|\.h$||' | sort)

{
cat <<'EOF'
/**
 * base16.h: Aggregate header for all Base16 and Base24 color schemes.
 *
 * This file is generated by scripts/build-aggregate.sh. Do not edit it
 * directly. To regenerate it, run:
 *
 *     scripts/build-aggregate.sh
 *
 * Every scheme is opt-in so that including this header costs nothing by
 * default. Define one or more of the following macros before including it:
 *
 * - BASE16_SCHEME_<SLUG>: include a single Base16 scheme, where <SLUG> is the
 *   scheme slug uppercased with dashes replaced by underscores. For example,
 *   define BASE16_SCHEME_DRACULA for base16-dracula.h.
 * - BASE24_SCHEME_<SLUG>: include a single Base24 scheme. For example, define
 *   BASE24_SCHEME_DRACULA for base24-dracula.h.
 * - BASE16_ALL: include every Base16 and Base24 scheme.
 * - BASE24_ALL: include every Base24 scheme.
 * - BASE16_SCHEME_LIST: define a registry of the selected schemes for
 *   enumeration. When BASE16_IMPLEMENTATION is also defined, this provides
 *   base16_scheme_list, a NULL-terminated array of pointers to the selected
 *   schemes, along with base16_scheme_list_count.
 *
 * The usual stb-style macros from the individual scheme headers apply here as
 * well: define BASE16_IMPLEMENTATION in exactly one translation unit to
 * provide the scheme definitions, or BASE16_HEADER_ONLY to suppress them.
 *
 * base16-c: https://github.com/RobLoach/base16-c
 *
 * License: MIT
 *
 * Copyright (c) 2024 Rob Loach (https://robloach.net)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BASE16_COLOR_H__
#define BASE16_COLOR_H__

/**
 * A single color used for Base16 or Base24.
 */
typedef struct base16_color {
    unsigned char r; /** Red channel */
    unsigned char g; /** Green channel */
    unsigned char b; /** Blue channel */
} base16_color;

#endif /* BASE16_COLOR_H__ */

#ifndef BASE16_SCHEME_H__
#define BASE16_SCHEME_H__

/**
 * A Base16 Scheme.
 */
typedef struct base16_scheme {
    const char *name; /** The name of the scheme. */
    base16_color base[24]; /** An array of the base16 colors for the scheme. */
    unsigned char system; /** Which system the scheme was built for, either 16 or 24. */
} base16_scheme;

#endif  /* BASE16_SCHEME_H__ */
EOF

echo ""
echo "/* Base16 schemes */"
for slug in $base16_slugs; do
    echo ""
    echo "#if defined(BASE16_ALL) || defined(BASE16_SCHEME_$(macro_slug "$slug"))"
    echo "#include \"base16-$slug.h\""
    echo "#endif"
done

echo ""
echo "/* Base24 schemes */"
for slug in $base24_slugs; do
    echo ""
    echo "#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_$(macro_slug "$slug"))"
    echo "#include \"base24-$slug.h\""
    echo "#endif"
done

cat <<'EOF'

/* Scheme registry, available when BASE16_SCHEME_LIST is defined. */
#if defined(BASE16_SCHEME_LIST)
#ifndef BASE16_SCHEME_LIST_H__
#define BASE16_SCHEME_LIST_H__

#include <stddef.h> /* size_t, NULL */

/**
 * A NULL-terminated array of pointers to all of the selected schemes.
 */
extern const base16_scheme *base16_scheme_list[];

/**
 * The number of schemes in base16_scheme_list, excluding the trailing NULL.
 */
extern const size_t base16_scheme_list_count;

#endif  /* BASE16_SCHEME_LIST_H__ */

#if defined(BASE16_IMPLEMENTATION) && !defined(BASE16_HEADER_ONLY)
#ifndef BASE16_SCHEME_LIST_IMPLEMENTATION_ONCE
#define BASE16_SCHEME_LIST_IMPLEMENTATION_ONCE

const base16_scheme *base16_scheme_list[] = {
EOF

for slug in $base16_slugs; do
    echo "#if defined(BASE16_ALL) || defined(BASE16_SCHEME_$(macro_slug "$slug"))"
    echo "    &base16_$(symbol_slug "$slug"),"
    echo "#endif"
done
for slug in $base24_slugs; do
    echo "#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_$(macro_slug "$slug"))"
    echo "    &base24_$(symbol_slug "$slug"),"
    echo "#endif"
done

cat <<'EOF'
    NULL /* Sentinel, so that the array is never empty. */
};

const size_t base16_scheme_list_count = sizeof(base16_scheme_list) / sizeof(base16_scheme_list[0]) - 1;

#endif  /* BASE16_SCHEME_LIST_IMPLEMENTATION_ONCE */
#endif  /* BASE16_IMPLEMENTATION */
#endif  /* BASE16_SCHEME_LIST */
EOF
} > "$tmp"

mv "$tmp" "$out"

echo "Generated $out"
