/**
 * base16.h: Aggregate header for all Base16 and Base24 color schemes.
 *
 * This file is generated by scripts/build-aggregate.sh. Do not edit it
 * directly. To regenerate it, run:
 *
 *     scripts/build-aggregate.sh
 *
 * Every scheme is opt-in so that including this header costs nothing by
 * default. Define one or more of the following macros before including it:
 *
 * - BASE16_SCHEME_<SLUG>: include a single Base16 scheme, where <SLUG> is the
 *   scheme slug uppercased with dashes replaced by underscores. For example,
 *   define BASE16_SCHEME_DRACULA for base16-dracula.h.
 * - BASE24_SCHEME_<SLUG>: include a single Base24 scheme. For example, define
 *   BASE24_SCHEME_DRACULA for base24-dracula.h.
 * - BASE16_ALL: include every Base16 and Base24 scheme.
 * - BASE24_ALL: include every Base24 scheme.
 * - BASE16_SCHEME_LIST: define a registry of the selected schemes for
 *   enumeration. When BASE16_IMPLEMENTATION is also defined, this provides
 *   base16_scheme_list, a NULL-terminated array of pointers to the selected
 *   schemes, along with base16_scheme_list_count.
 *
 * The usual stb-style macros from the individual scheme headers apply here as
 * well: define BASE16_IMPLEMENTATION in exactly one translation unit to
 * provide the scheme definitions, or BASE16_HEADER_ONLY to suppress them.
 *
 * base16-c: https://github.com/RobLoach/base16-c
 *
 * License: MIT
 *
 * Copyright (c) 2024 Rob Loach (https://robloach.net)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BASE16_COLOR_H__
#define BASE16_COLOR_H__

/**
 * A single color used for Base16 or Base24.
 */
typedef struct base16_color {
    unsigned char r; /** Red channel */
    unsigned char g; /** Green channel */
    unsigned char b; /** Blue channel */
} base16_color;

#endif /* BASE16_COLOR_H__ */

#ifndef BASE16_SCHEME_H__
#define BASE16_SCHEME_H__

/**
 * A Base16 Scheme.
 */
typedef struct base16_scheme {
    const char *name; /** The name of the scheme. */
    base16_color base[24]; /** An array of the base16 colors for the scheme. */
    unsigned char system; /** Which system the scheme was built for, either 16 or 24. */
} base16_scheme;

#endif  /* BASE16_SCHEME_H__ */

/* Base16 schemes */

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_3024)
#include "base16-3024.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_APATHY)
#include "base16-apathy.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_APPRENTICE)
#include "base16-apprentice.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ASHES)
#include "base16-ashes.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_CAVE)
#include "base16-atelier-cave.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_CAVE_LIGHT)
#include "base16-atelier-cave-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_DUNE)
#include "base16-atelier-dune.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_DUNE_LIGHT)
#include "base16-atelier-dune-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_ESTUARY)
#include "base16-atelier-estuary.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_ESTUARY_LIGHT)
#include "base16-atelier-estuary-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_FOREST)
#include "base16-atelier-forest.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_FOREST_LIGHT)
#include "base16-atelier-forest-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_HEATH)
#include "base16-atelier-heath.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_HEATH_LIGHT)
#include "base16-atelier-heath-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_LAKESIDE)
#include "base16-atelier-lakeside.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_LAKESIDE_LIGHT)
#include "base16-atelier-lakeside-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_PLATEAU)
#include "base16-atelier-plateau.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_PLATEAU_LIGHT)
#include "base16-atelier-plateau-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SAVANNA)
#include "base16-atelier-savanna.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SAVANNA_LIGHT)
#include "base16-atelier-savanna-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SEASIDE)
#include "base16-atelier-seaside.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SEASIDE_LIGHT)
#include "base16-atelier-seaside-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SULPHURPOOL)
#include "base16-atelier-sulphurpool.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SULPHURPOOL_LIGHT)
#include "base16-atelier-sulphurpool-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATLAS)
#include "base16-atlas.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_AYU_DARK)
#include "base16-ayu-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_AYU_LIGHT)
#include "base16-ayu-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_AYU_MIRAGE)
#include "base16-ayu-mirage.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_AZTEC)
#include "base16-aztec.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BESPIN)
#include "base16-bespin.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL)
#include "base16-black-metal.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_BATHORY)
#include "base16-black-metal-bathory.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_BURZUM)
#include "base16-black-metal-burzum.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_DARK_FUNERAL)
#include "base16-black-metal-dark-funeral.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_GORGOROTH)
#include "base16-black-metal-gorgoroth.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_IMMORTAL)
#include "base16-black-metal-immortal.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_KHOLD)
#include "base16-black-metal-khold.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_MARDUK)
#include "base16-black-metal-marduk.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_MAYHEM)
#include "base16-black-metal-mayhem.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_NILE)
#include "base16-black-metal-nile.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_VENOM)
#include "base16-black-metal-venom.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLUEFOREST)
#include "base16-blueforest.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLUEISH)
#include "base16-blueish.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BREWER)
#include "base16-brewer.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BRIGHT)
#include "base16-bright.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BROGRAMMER)
#include "base16-brogrammer.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BRUSHTREES)
#include "base16-brushtrees.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BRUSHTREES_DARK)
#include "base16-brushtrees-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CAROLINE)
#include "base16-caroline.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CATPPUCCIN_FRAPPE)
#include "base16-catppuccin-frappe.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CATPPUCCIN_LATTE)
#include "base16-catppuccin-latte.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CATPPUCCIN_MACCHIATO)
#include "base16-catppuccin-macchiato.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CATPPUCCIN_MOCHA)
#include "base16-catppuccin-mocha.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CHALK)
#include "base16-chalk.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CIRCUS)
#include "base16-circus.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CLASSIC_DARK)
#include "base16-classic-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CLASSIC_LIGHT)
#include "base16-classic-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CODESCHOOL)
#include "base16-codeschool.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_COLORS)
#include "base16-colors.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CUPCAKE)
#include "base16-cupcake.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CUPERTINO)
#include "base16-cupertino.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_BLACK)
#include "base16-da-one-black.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_GRAY)
#include "base16-da-one-gray.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_OCEAN)
#include "base16-da-one-ocean.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_PAPER)
#include "base16-da-one-paper.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_SEA)
#include "base16-da-one-sea.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_WHITE)
#include "base16-da-one-white.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DANQING)
#include "base16-danqing.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DANQING_LIGHT)
#include "base16-danqing-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DARCULA)
#include "base16-darcula.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DARKMOSS)
#include "base16-darkmoss.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DARKTOOTH)
#include "base16-darktooth.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DARKVIOLET)
#include "base16-darkviolet.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DECAF)
#include "base16-decaf.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DEEP_OCEANIC_NEXT)
#include "base16-deep-oceanic-next.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DEFAULT_DARK)
#include "base16-default-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DEFAULT_LIGHT)
#include "base16-default-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DIRTYSEA)
#include "base16-dirtysea.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DRACULA)
#include "base16-dracula.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EDGE_DARK)
#include "base16-edge-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EDGE_LIGHT)
#include "base16-edge-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EIGHTIES)
#include "base16-eighties.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EMBERS)
#include "base16-embers.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EMBERS_LIGHT)
#include "base16-embers-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EMIL)
#include "base16-emil.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EQUILIBRIUM_DARK)
#include "base16-equilibrium-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EQUILIBRIUM_GRAY_DARK)
#include "base16-equilibrium-gray-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EQUILIBRIUM_GRAY_LIGHT)
#include "base16-equilibrium-gray-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EQUILIBRIUM_LIGHT)
#include "base16-equilibrium-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ERIS)
#include "base16-eris.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ESPRESSO)
#include "base16-espresso.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVA)
#include "base16-eva.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVA_DIM)
#include "base16-eva-dim.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVENOK_DARK)
#include "base16-evenok-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVERFOREST)
#include "base16-everforest.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVERFOREST_DARK_HARD)
#include "base16-everforest-dark-hard.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_FLAT)
#include "base16-flat.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_FRAMER)
#include "base16-framer.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_FRUIT_SODA)
#include "base16-fruit-soda.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GIGAVOLT)
#include "base16-gigavolt.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GITHUB)
#include "base16-github.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GOOGLE_DARK)
#include "base16-google-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GOOGLE_LIGHT)
#include "base16-google-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GOTHAM)
#include "base16-gotham.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRAYSCALE_DARK)
#include "base16-grayscale-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRAYSCALE_LIGHT)
#include "base16-grayscale-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GREENSCREEN)
#include "base16-greenscreen.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUBER)
#include "base16-gruber.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_DARK_HARD)
#include "base16-gruvbox-dark-hard.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_DARK_MEDIUM)
#include "base16-gruvbox-dark-medium.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_DARK_PALE)
#include "base16-gruvbox-dark-pale.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_DARK_SOFT)
#include "base16-gruvbox-dark-soft.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_LIGHT_HARD)
#include "base16-gruvbox-light-hard.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_LIGHT_MEDIUM)
#include "base16-gruvbox-light-medium.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_LIGHT_SOFT)
#include "base16-gruvbox-light-soft.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_DARK_HARD)
#include "base16-gruvbox-material-dark-hard.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_DARK_MEDIUM)
#include "base16-gruvbox-material-dark-medium.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_DARK_SOFT)
#include "base16-gruvbox-material-dark-soft.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_LIGHT_HARD)
#include "base16-gruvbox-material-light-hard.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_LIGHT_MEDIUM)
#include "base16-gruvbox-material-light-medium.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_LIGHT_SOFT)
#include "base16-gruvbox-material-light-soft.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HARDCORE)
#include "base16-hardcore.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HARMONIC16_DARK)
#include "base16-harmonic16-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HARMONIC16_LIGHT)
#include "base16-harmonic16-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HEETCH)
#include "base16-heetch.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HEETCH_LIGHT)
#include "base16-heetch-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HELIOS)
#include "base16-helios.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HOPSCOTCH)
#include "base16-hopscotch.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HORIZON_DARK)
#include "base16-horizon-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HORIZON_LIGHT)
#include "base16-horizon-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HORIZON_TERMINAL_DARK)
#include "base16-horizon-terminal-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HORIZON_TERMINAL_LIGHT)
#include "base16-horizon-terminal-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HUMANOID_DARK)
#include "base16-humanoid-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HUMANOID_LIGHT)
#include "base16-humanoid-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_IA_DARK)
#include "base16-ia-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_IA_LIGHT)
#include "base16-ia-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ICY)
#include "base16-icy.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_IRBLACK)
#include "base16-irblack.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ISOTOPE)
#include "base16-isotope.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_JABUTI)
#include "base16-jabuti.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_KANAGAWA)
#include "base16-kanagawa.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_KATY)
#include "base16-katy.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_KIMBER)
#include "base16-kimber.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_LIME)
#include "base16-lime.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MACINTOSH)
#include "base16-macintosh.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MARRAKESH)
#include "base16-marrakesh.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIA)
#include "base16-materia.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL)
#include "base16-material.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL_DARKER)
#include "base16-material-darker.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL_LIGHTER)
#include "base16-material-lighter.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL_PALENIGHT)
#include "base16-material-palenight.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL_VIVID)
#include "base16-material-vivid.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MEASURED_DARK)
#include "base16-measured-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MEASURED_LIGHT)
#include "base16-measured-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MELLOW_PURPLE)
#include "base16-mellow-purple.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MEXICO_LIGHT)
#include "base16-mexico-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MOCHA)
#include "base16-mocha.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MONOKAI)
#include "base16-monokai.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MOONLIGHT)
#include "base16-moonlight.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MOUNTAIN)
#include "base16-mountain.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_NEBULA)
#include "base16-nebula.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_NORD)
#include "base16-nord.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_NORD_LIGHT)
#include "base16-nord-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_NOVA)
#include "base16-nova.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OCEAN)
#include "base16-ocean.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OCEANICNEXT)
#include "base16-oceanicnext.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ONE_LIGHT)
#include "base16-one-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ONEDARK)
#include "base16-onedark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ONEDARK_DARK)
#include "base16-onedark-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OUTRUN_DARK)
#include "base16-outrun-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OXOCARBON_DARK)
#include "base16-oxocarbon-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OXOCARBON_LIGHT)
#include "base16-oxocarbon-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PANDORA)
#include "base16-pandora.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PAPERCOLOR_DARK)
#include "base16-papercolor-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PAPERCOLOR_LIGHT)
#include "base16-papercolor-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PARAISO)
#include "base16-paraiso.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PASQUE)
#include "base16-pasque.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PHD)
#include "base16-phd.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PICO)
#include "base16-pico.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PINKY)
#include "base16-pinky.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_POP)
#include "base16-pop.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PORPLE)
#include "base16-porple.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRECIOUS_DARK_ELEVEN)
#include "base16-precious-dark-eleven.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRECIOUS_DARK_FIFTEEN)
#include "base16-precious-dark-fifteen.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRECIOUS_LIGHT_WARM)
#include "base16-precious-light-warm.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRECIOUS_LIGHT_WHITE)
#include "base16-precious-light-white.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRIMER_DARK)
#include "base16-primer-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRIMER_DARK_DIMMED)
#include "base16-primer-dark-dimmed.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRIMER_LIGHT)
#include "base16-primer-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PURPLEDREAM)
#include "base16-purpledream.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_QUALIA)
#include "base16-qualia.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_RAILSCASTS)
#include "base16-railscasts.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_REBECCA)
#include "base16-rebecca.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ROSE_PINE)
#include "base16-rose-pine.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ROSE_PINE_DAWN)
#include "base16-rose-pine-dawn.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ROSE_PINE_MOON)
#include "base16-rose-pine-moon.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SAGA)
#include "base16-saga.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SAGELIGHT)
#include "base16-sagelight.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SAKURA)
#include "base16-sakura.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SANDCASTLE)
#include "base16-sandcastle.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SELENIZED_BLACK)
#include "base16-selenized-black.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SELENIZED_DARK)
#include "base16-selenized-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SELENIZED_LIGHT)
#include "base16-selenized-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SELENIZED_WHITE)
#include "base16-selenized-white.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SETI)
#include "base16-seti.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SHADES_OF_PURPLE)
#include "base16-shades-of-purple.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SHADESMEAR_DARK)
#include "base16-shadesmear-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SHADESMEAR_LIGHT)
#include "base16-shadesmear-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SHAPESHIFTER)
#include "base16-shapeshifter.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SILK_DARK)
#include "base16-silk-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SILK_LIGHT)
#include "base16-silk-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SNAZZY)
#include "base16-snazzy.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SOLARFLARE)
#include "base16-solarflare.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SOLARFLARE_LIGHT)
#include "base16-solarflare-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SOLARIZED_DARK)
#include "base16-solarized-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SOLARIZED_LIGHT)
#include "base16-solarized-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SPACEDUCK)
#include "base16-spaceduck.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SPACEMACS)
#include "base16-spacemacs.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SPARKY)
#include "base16-sparky.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_STANDARDIZED_DARK)
#include "base16-standardized-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_STANDARDIZED_LIGHT)
#include "base16-standardized-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_STELLA)
#include "base16-stella.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_STILL_ALIVE)
#include "base16-still-alive.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SUMMERCAMP)
#include "base16-summercamp.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SUMMERFRUIT_DARK)
#include "base16-summerfruit-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SUMMERFRUIT_LIGHT)
#include "base16-summerfruit-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SYNTH_MIDNIGHT_DARK)
#include "base16-synth-midnight-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SYNTH_MIDNIGHT_LIGHT)
#include "base16-synth-midnight-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TANGO)
#include "base16-tango.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TAROT)
#include "base16-tarot.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TENDER)
#include "base16-tender.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TERRACOTTA)
#include "base16-terracotta.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TERRACOTTA_DARK)
#include "base16-terracotta-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_CITY_DARK)
#include "base16-tokyo-city-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_CITY_LIGHT)
#include "base16-tokyo-city-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_CITY_TERMINAL_DARK)
#include "base16-tokyo-city-terminal-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_CITY_TERMINAL_LIGHT)
#include "base16-tokyo-city-terminal-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_DARK)
#include "base16-tokyo-night-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_LIGHT)
#include "base16-tokyo-night-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_MOON)
#include "base16-tokyo-night-moon.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_STORM)
#include "base16-tokyo-night-storm.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_TERMINAL_DARK)
#include "base16-tokyo-night-terminal-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_TERMINAL_LIGHT)
#include "base16-tokyo-night-terminal-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_TERMINAL_STORM)
#include "base16-tokyo-night-terminal-storm.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYODARK)
#include "base16-tokyodark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYODARK_TERMINAL)
#include "base16-tokyodark-terminal.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOMORROW)
#include "base16-tomorrow.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOMORROW_NIGHT)
#include "base16-tomorrow-night.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOMORROW_NIGHT_EIGHTIES)
#include "base16-tomorrow-night-eighties.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TUBE)
#include "base16-tube.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TWILIGHT)
#include "base16-twilight.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_UNIKITTY_DARK)
#include "base16-unikitty-dark.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_UNIKITTY_LIGHT)
#include "base16-unikitty-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_UNIKITTY_REVERSIBLE)
#include "base16-unikitty-reversible.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_UWUNICORN)
#include "base16-uwunicorn.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_VESPER)
#include "base16-vesper.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_VICE)
#include "base16-vice.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_VULCAN)
#include "base16-vulcan.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_10)
#include "base16-windows-10.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_10_LIGHT)
#include "base16-windows-10-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_95)
#include "base16-windows-95.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_95_LIGHT)
#include "base16-windows-95-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_HIGHCONTRAST)
#include "base16-windows-highcontrast.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_HIGHCONTRAST_LIGHT)
#include "base16-windows-highcontrast-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_NT)
#include "base16-windows-nt.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_NT_LIGHT)
#include "base16-windows-nt-light.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WOODLAND)
#include "base16-woodland.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_XCODE_DUSK)
#include "base16-xcode-dusk.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ZENBONES)
#include "base16-zenbones.h"
#endif

#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ZENBURN)
#include "base16-zenburn.h"
#endif

/* Base24 schemes */

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_BROGRAMMER)
#include "base24-brogrammer.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_CHALK)
#include "base24-chalk.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_DEEP_OCEANIC_NEXT)
#include "base24-deep-oceanic-next.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_DRACULA)
#include "base24-dracula.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_ESPRESSO)
#include "base24-espresso.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_FLAT)
#include "base24-flat.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_FRAMER)
#include "base24-framer.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_GITHUB)
#include "base24-github.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_HARDCORE)
#include "base24-hardcore.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_ONE_BLACK)
#include "base24-one-black.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_ONE_DARK)
#include "base24-one-dark.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_ONE_LIGHT)
#include "base24-one-light.h"
#endif

#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_SPARKY)
#include "base24-sparky.h"
#endif

/* Scheme registry, available when BASE16_SCHEME_LIST is defined. */
#if defined(BASE16_SCHEME_LIST)
#ifndef BASE16_SCHEME_LIST_H__
#define BASE16_SCHEME_LIST_H__

#include <stddef.h> /* size_t, NULL */

/**
 * A NULL-terminated array of pointers to all of the selected schemes.
 */
extern const base16_scheme *base16_scheme_list[];

/**
 * The number of schemes in base16_scheme_list, excluding the trailing NULL.
 */
extern const size_t base16_scheme_list_count;

#endif  /* BASE16_SCHEME_LIST_H__ */

#if defined(BASE16_IMPLEMENTATION) && !defined(BASE16_HEADER_ONLY)
#ifndef BASE16_SCHEME_LIST_IMPLEMENTATION_ONCE
#define BASE16_SCHEME_LIST_IMPLEMENTATION_ONCE

const base16_scheme *base16_scheme_list[] = {
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_3024)
    &base16_3024,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_APATHY)
    &base16_apathy,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_APPRENTICE)
    &base16_apprentice,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ASHES)
    &base16_ashes,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_CAVE)
    &base16_atelier_cave,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_CAVE_LIGHT)
    &base16_atelier_cave_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_DUNE)
    &base16_atelier_dune,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_DUNE_LIGHT)
    &base16_atelier_dune_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_ESTUARY)
    &base16_atelier_estuary,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_ESTUARY_LIGHT)
    &base16_atelier_estuary_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_FOREST)
    &base16_atelier_forest,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_FOREST_LIGHT)
    &base16_atelier_forest_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_HEATH)
    &base16_atelier_heath,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_HEATH_LIGHT)
    &base16_atelier_heath_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_LAKESIDE)
    &base16_atelier_lakeside,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_LAKESIDE_LIGHT)
    &base16_atelier_lakeside_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_PLATEAU)
    &base16_atelier_plateau,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_PLATEAU_LIGHT)
    &base16_atelier_plateau_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SAVANNA)
    &base16_atelier_savanna,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SAVANNA_LIGHT)
    &base16_atelier_savanna_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SEASIDE)
    &base16_atelier_seaside,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SEASIDE_LIGHT)
    &base16_atelier_seaside_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SULPHURPOOL)
    &base16_atelier_sulphurpool,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATELIER_SULPHURPOOL_LIGHT)
    &base16_atelier_sulphurpool_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ATLAS)
    &base16_atlas,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_AYU_DARK)
    &base16_ayu_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_AYU_LIGHT)
    &base16_ayu_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_AYU_MIRAGE)
    &base16_ayu_mirage,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_AZTEC)
    &base16_aztec,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BESPIN)
    &base16_bespin,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL)
    &base16_black_metal,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_BATHORY)
    &base16_black_metal_bathory,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_BURZUM)
    &base16_black_metal_burzum,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_DARK_FUNERAL)
    &base16_black_metal_dark_funeral,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_GORGOROTH)
    &base16_black_metal_gorgoroth,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_IMMORTAL)
    &base16_black_metal_immortal,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_KHOLD)
    &base16_black_metal_khold,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_MARDUK)
    &base16_black_metal_marduk,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_MAYHEM)
    &base16_black_metal_mayhem,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_NILE)
    &base16_black_metal_nile,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLACK_METAL_VENOM)
    &base16_black_metal_venom,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLUEFOREST)
    &base16_blueforest,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BLUEISH)
    &base16_blueish,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BREWER)
    &base16_brewer,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BRIGHT)
    &base16_bright,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BROGRAMMER)
    &base16_brogrammer,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BRUSHTREES)
    &base16_brushtrees,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_BRUSHTREES_DARK)
    &base16_brushtrees_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CAROLINE)
    &base16_caroline,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CATPPUCCIN_FRAPPE)
    &base16_catppuccin_frappe,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CATPPUCCIN_LATTE)
    &base16_catppuccin_latte,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CATPPUCCIN_MACCHIATO)
    &base16_catppuccin_macchiato,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CATPPUCCIN_MOCHA)
    &base16_catppuccin_mocha,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CHALK)
    &base16_chalk,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CIRCUS)
    &base16_circus,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CLASSIC_DARK)
    &base16_classic_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CLASSIC_LIGHT)
    &base16_classic_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CODESCHOOL)
    &base16_codeschool,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_COLORS)
    &base16_colors,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CUPCAKE)
    &base16_cupcake,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_CUPERTINO)
    &base16_cupertino,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_BLACK)
    &base16_da_one_black,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_GRAY)
    &base16_da_one_gray,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_OCEAN)
    &base16_da_one_ocean,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_PAPER)
    &base16_da_one_paper,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_SEA)
    &base16_da_one_sea,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DA_ONE_WHITE)
    &base16_da_one_white,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DANQING)
    &base16_danqing,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DANQING_LIGHT)
    &base16_danqing_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DARCULA)
    &base16_darcula,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DARKMOSS)
    &base16_darkmoss,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DARKTOOTH)
    &base16_darktooth,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DARKVIOLET)
    &base16_darkviolet,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DECAF)
    &base16_decaf,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DEEP_OCEANIC_NEXT)
    &base16_deep_oceanic_next,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DEFAULT_DARK)
    &base16_default_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DEFAULT_LIGHT)
    &base16_default_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DIRTYSEA)
    &base16_dirtysea,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_DRACULA)
    &base16_dracula,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EDGE_DARK)
    &base16_edge_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EDGE_LIGHT)
    &base16_edge_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EIGHTIES)
    &base16_eighties,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EMBERS)
    &base16_embers,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EMBERS_LIGHT)
    &base16_embers_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EMIL)
    &base16_emil,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EQUILIBRIUM_DARK)
    &base16_equilibrium_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EQUILIBRIUM_GRAY_DARK)
    &base16_equilibrium_gray_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EQUILIBRIUM_GRAY_LIGHT)
    &base16_equilibrium_gray_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EQUILIBRIUM_LIGHT)
    &base16_equilibrium_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ERIS)
    &base16_eris,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ESPRESSO)
    &base16_espresso,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVA)
    &base16_eva,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVA_DIM)
    &base16_eva_dim,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVENOK_DARK)
    &base16_evenok_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVERFOREST)
    &base16_everforest,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_EVERFOREST_DARK_HARD)
    &base16_everforest_dark_hard,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_FLAT)
    &base16_flat,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_FRAMER)
    &base16_framer,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_FRUIT_SODA)
    &base16_fruit_soda,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GIGAVOLT)
    &base16_gigavolt,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GITHUB)
    &base16_github,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GOOGLE_DARK)
    &base16_google_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GOOGLE_LIGHT)
    &base16_google_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GOTHAM)
    &base16_gotham,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRAYSCALE_DARK)
    &base16_grayscale_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRAYSCALE_LIGHT)
    &base16_grayscale_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GREENSCREEN)
    &base16_greenscreen,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUBER)
    &base16_gruber,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_DARK_HARD)
    &base16_gruvbox_dark_hard,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_DARK_MEDIUM)
    &base16_gruvbox_dark_medium,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_DARK_PALE)
    &base16_gruvbox_dark_pale,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_DARK_SOFT)
    &base16_gruvbox_dark_soft,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_LIGHT_HARD)
    &base16_gruvbox_light_hard,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_LIGHT_MEDIUM)
    &base16_gruvbox_light_medium,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_LIGHT_SOFT)
    &base16_gruvbox_light_soft,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_DARK_HARD)
    &base16_gruvbox_material_dark_hard,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_DARK_MEDIUM)
    &base16_gruvbox_material_dark_medium,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_DARK_SOFT)
    &base16_gruvbox_material_dark_soft,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_LIGHT_HARD)
    &base16_gruvbox_material_light_hard,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_LIGHT_MEDIUM)
    &base16_gruvbox_material_light_medium,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_GRUVBOX_MATERIAL_LIGHT_SOFT)
    &base16_gruvbox_material_light_soft,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HARDCORE)
    &base16_hardcore,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HARMONIC16_DARK)
    &base16_harmonic16_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HARMONIC16_LIGHT)
    &base16_harmonic16_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HEETCH)
    &base16_heetch,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HEETCH_LIGHT)
    &base16_heetch_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HELIOS)
    &base16_helios,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HOPSCOTCH)
    &base16_hopscotch,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HORIZON_DARK)
    &base16_horizon_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HORIZON_LIGHT)
    &base16_horizon_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HORIZON_TERMINAL_DARK)
    &base16_horizon_terminal_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HORIZON_TERMINAL_LIGHT)
    &base16_horizon_terminal_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HUMANOID_DARK)
    &base16_humanoid_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_HUMANOID_LIGHT)
    &base16_humanoid_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_IA_DARK)
    &base16_ia_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_IA_LIGHT)
    &base16_ia_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ICY)
    &base16_icy,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_IRBLACK)
    &base16_irblack,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ISOTOPE)
    &base16_isotope,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_JABUTI)
    &base16_jabuti,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_KANAGAWA)
    &base16_kanagawa,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_KATY)
    &base16_katy,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_KIMBER)
    &base16_kimber,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_LIME)
    &base16_lime,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MACINTOSH)
    &base16_macintosh,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MARRAKESH)
    &base16_marrakesh,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIA)
    &base16_materia,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL)
    &base16_material,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL_DARKER)
    &base16_material_darker,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL_LIGHTER)
    &base16_material_lighter,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL_PALENIGHT)
    &base16_material_palenight,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MATERIAL_VIVID)
    &base16_material_vivid,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MEASURED_DARK)
    &base16_measured_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MEASURED_LIGHT)
    &base16_measured_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MELLOW_PURPLE)
    &base16_mellow_purple,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MEXICO_LIGHT)
    &base16_mexico_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MOCHA)
    &base16_mocha,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MONOKAI)
    &base16_monokai,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MOONLIGHT)
    &base16_moonlight,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_MOUNTAIN)
    &base16_mountain,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_NEBULA)
    &base16_nebula,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_NORD)
    &base16_nord,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_NORD_LIGHT)
    &base16_nord_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_NOVA)
    &base16_nova,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OCEAN)
    &base16_ocean,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OCEANICNEXT)
    &base16_oceanicnext,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ONE_LIGHT)
    &base16_one_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ONEDARK)
    &base16_onedark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ONEDARK_DARK)
    &base16_onedark_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OUTRUN_DARK)
    &base16_outrun_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OXOCARBON_DARK)
    &base16_oxocarbon_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_OXOCARBON_LIGHT)
    &base16_oxocarbon_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PANDORA)
    &base16_pandora,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PAPERCOLOR_DARK)
    &base16_papercolor_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PAPERCOLOR_LIGHT)
    &base16_papercolor_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PARAISO)
    &base16_paraiso,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PASQUE)
    &base16_pasque,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PHD)
    &base16_phd,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PICO)
    &base16_pico,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PINKY)
    &base16_pinky,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_POP)
    &base16_pop,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PORPLE)
    &base16_porple,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRECIOUS_DARK_ELEVEN)
    &base16_precious_dark_eleven,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRECIOUS_DARK_FIFTEEN)
    &base16_precious_dark_fifteen,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRECIOUS_LIGHT_WARM)
    &base16_precious_light_warm,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRECIOUS_LIGHT_WHITE)
    &base16_precious_light_white,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRIMER_DARK)
    &base16_primer_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRIMER_DARK_DIMMED)
    &base16_primer_dark_dimmed,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PRIMER_LIGHT)
    &base16_primer_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_PURPLEDREAM)
    &base16_purpledream,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_QUALIA)
    &base16_qualia,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_RAILSCASTS)
    &base16_railscasts,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_REBECCA)
    &base16_rebecca,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ROSE_PINE)
    &base16_rose_pine,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ROSE_PINE_DAWN)
    &base16_rose_pine_dawn,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ROSE_PINE_MOON)
    &base16_rose_pine_moon,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SAGA)
    &base16_saga,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SAGELIGHT)
    &base16_sagelight,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SAKURA)
    &base16_sakura,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SANDCASTLE)
    &base16_sandcastle,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SELENIZED_BLACK)
    &base16_selenized_black,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SELENIZED_DARK)
    &base16_selenized_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SELENIZED_LIGHT)
    &base16_selenized_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SELENIZED_WHITE)
    &base16_selenized_white,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SETI)
    &base16_seti,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SHADES_OF_PURPLE)
    &base16_shades_of_purple,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SHADESMEAR_DARK)
    &base16_shadesmear_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SHADESMEAR_LIGHT)
    &base16_shadesmear_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SHAPESHIFTER)
    &base16_shapeshifter,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SILK_DARK)
    &base16_silk_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SILK_LIGHT)
    &base16_silk_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SNAZZY)
    &base16_snazzy,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SOLARFLARE)
    &base16_solarflare,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SOLARFLARE_LIGHT)
    &base16_solarflare_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SOLARIZED_DARK)
    &base16_solarized_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SOLARIZED_LIGHT)
    &base16_solarized_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SPACEDUCK)
    &base16_spaceduck,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SPACEMACS)
    &base16_spacemacs,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SPARKY)
    &base16_sparky,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_STANDARDIZED_DARK)
    &base16_standardized_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_STANDARDIZED_LIGHT)
    &base16_standardized_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_STELLA)
    &base16_stella,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_STILL_ALIVE)
    &base16_still_alive,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SUMMERCAMP)
    &base16_summercamp,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SUMMERFRUIT_DARK)
    &base16_summerfruit_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SUMMERFRUIT_LIGHT)
    &base16_summerfruit_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SYNTH_MIDNIGHT_DARK)
    &base16_synth_midnight_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_SYNTH_MIDNIGHT_LIGHT)
    &base16_synth_midnight_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TANGO)
    &base16_tango,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TAROT)
    &base16_tarot,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TENDER)
    &base16_tender,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TERRACOTTA)
    &base16_terracotta,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TERRACOTTA_DARK)
    &base16_terracotta_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_CITY_DARK)
    &base16_tokyo_city_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_CITY_LIGHT)
    &base16_tokyo_city_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_CITY_TERMINAL_DARK)
    &base16_tokyo_city_terminal_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_CITY_TERMINAL_LIGHT)
    &base16_tokyo_city_terminal_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_DARK)
    &base16_tokyo_night_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_LIGHT)
    &base16_tokyo_night_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_MOON)
    &base16_tokyo_night_moon,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_STORM)
    &base16_tokyo_night_storm,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_TERMINAL_DARK)
    &base16_tokyo_night_terminal_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_TERMINAL_LIGHT)
    &base16_tokyo_night_terminal_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYO_NIGHT_TERMINAL_STORM)
    &base16_tokyo_night_terminal_storm,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYODARK)
    &base16_tokyodark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOKYODARK_TERMINAL)
    &base16_tokyodark_terminal,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOMORROW)
    &base16_tomorrow,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOMORROW_NIGHT)
    &base16_tomorrow_night,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TOMORROW_NIGHT_EIGHTIES)
    &base16_tomorrow_night_eighties,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TUBE)
    &base16_tube,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_TWILIGHT)
    &base16_twilight,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_UNIKITTY_DARK)
    &base16_unikitty_dark,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_UNIKITTY_LIGHT)
    &base16_unikitty_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_UNIKITTY_REVERSIBLE)
    &base16_unikitty_reversible,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_UWUNICORN)
    &base16_uwunicorn,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_VESPER)
    &base16_vesper,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_VICE)
    &base16_vice,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_VULCAN)
    &base16_vulcan,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_10)
    &base16_windows_10,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_10_LIGHT)
    &base16_windows_10_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_95)
    &base16_windows_95,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_95_LIGHT)
    &base16_windows_95_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_HIGHCONTRAST)
    &base16_windows_highcontrast,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_HIGHCONTRAST_LIGHT)
    &base16_windows_highcontrast_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_NT)
    &base16_windows_nt,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WINDOWS_NT_LIGHT)
    &base16_windows_nt_light,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_WOODLAND)
    &base16_woodland,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_XCODE_DUSK)
    &base16_xcode_dusk,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ZENBONES)
    &base16_zenbones,
#endif
#if defined(BASE16_ALL) || defined(BASE16_SCHEME_ZENBURN)
    &base16_zenburn,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_BROGRAMMER)
    &base24_brogrammer,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_CHALK)
    &base24_chalk,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_DEEP_OCEANIC_NEXT)
    &base24_deep_oceanic_next,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_DRACULA)
    &base24_dracula,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_ESPRESSO)
    &base24_espresso,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_FLAT)
    &base24_flat,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_FRAMER)
    &base24_framer,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_GITHUB)
    &base24_github,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_HARDCORE)
    &base24_hardcore,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_ONE_BLACK)
    &base24_one_black,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_ONE_DARK)
    &base24_one_dark,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_ONE_LIGHT)
    &base24_one_light,
#endif
#if defined(BASE24_ALL) || defined(BASE16_ALL) || defined(BASE24_SCHEME_SPARKY)
    &base24_sparky,
#endif
    NULL /* Sentinel, so that the array is never empty. */
};

const size_t base16_scheme_list_count = sizeof(base16_scheme_list) / sizeof(base16_scheme_list[0]) - 1;

#endif  /* BASE16_SCHEME_LIST_IMPLEMENTATION_ONCE */
#endif  /* BASE16_IMPLEMENTATION */
#endif  /* BASE16_SCHEME_LIST */
