/**
 * base16-c: Base16 and Base24 header includes for C.
 * https://github.com/RobLoach/base16-c
 *
 * @author Rob Loach (https://github.com/RobLoach)
 *
 * License: MIT
 *
 * Copyright (c) 2024 Rob Loach (https://robloach.net)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef TINTED_C_H__
#define TINTED_C_H__

#include "base16-0x96f.h" /* dark */
#include "base16-3024.h" /* dark */
#include "base16-apathy.h" /* dark */
#include "base16-apprentice.h" /* dark */
#include "base16-arroz-con-dulce-dark.h" /* dark */
#include "base16-arroz-con-dulce.h" /* light */
#include "base16-ascendancy.h" /* dark */
#include "base16-ashes.h" /* dark */
#include "base16-atelier-cave-light.h" /* light */
#include "base16-atelier-cave.h" /* dark */
#include "base16-atelier-dune-light.h" /* light */
#include "base16-atelier-dune.h" /* dark */
#include "base16-atelier-estuary-light.h" /* light */
#include "base16-atelier-estuary.h" /* dark */
#include "base16-atelier-forest-light.h" /* light */
#include "base16-atelier-forest.h" /* dark */
#include "base16-atelier-heath-light.h" /* light */
#include "base16-atelier-heath.h" /* dark */
#include "base16-atelier-lakeside-light.h" /* light */
#include "base16-atelier-lakeside.h" /* dark */
#include "base16-atelier-plateau-light.h" /* light */
#include "base16-atelier-plateau.h" /* dark */
#include "base16-atelier-savanna-light.h" /* light */
#include "base16-atelier-savanna.h" /* dark */
#include "base16-atelier-seaside-light.h" /* light */
#include "base16-atelier-seaside.h" /* dark */
#include "base16-atelier-sulphurpool-light.h" /* light */
#include "base16-atelier-sulphurpool.h" /* dark */
#include "base16-atlas.h" /* dark */
#include "base16-ayu-dark.h" /* dark */
#include "base16-ayu-light.h" /* light */
#include "base16-ayu-mirage.h" /* dark */
#include "base16-aztec.h" /* dark */
#include "base16-bespin.h" /* dark */
#include "base16-black-metal-bathory.h" /* dark */
#include "base16-black-metal-burzum.h" /* dark */
#include "base16-black-metal-dark-funeral.h" /* dark */
#include "base16-black-metal-gorgoroth.h" /* dark */
#include "base16-black-metal-immortal.h" /* dark */
#include "base16-black-metal-khold.h" /* dark */
#include "base16-black-metal-marduk.h" /* dark */
#include "base16-black-metal-mayhem.h" /* dark */
#include "base16-black-metal-nile.h" /* dark */
#include "base16-black-metal-venom.h" /* dark */
#include "base16-black-metal.h" /* dark */
#include "base16-blueforest.h" /* dark */
#include "base16-blueish.h" /* dark */
#include "base16-boo-shnickle.h" /* dark */
#include "base16-boo-shnickle-light.h" /* light */
#include "base16-bosque.h" /* dark */
#include "base16-brasa.h" /* dark */
#include "base16-brewer.h" /* dark */
#include "base16-bright.h" /* dark */
#include "base16-brogrammer.h" /* dark */
#include "base16-brushtrees-dark.h" /* dark */
#include "base16-brushtrees.h" /* light */
#include "base16-cacao.h" /* dark */
#include "base16-caroline.h" /* dark */
#include "base16-catppuccin-frappe.h" /* dark */
#include "base16-catppuccin-latte.h" /* light */
#include "base16-catppuccin-macchiato.h" /* dark */
#include "base16-catppuccin-mocha.h" /* dark */
#include "base16-cerulean-signal-dark.h" /* dark */
#include "base16-cerulean-signal-light.h" /* light */
#include "base16-chalk.h" /* dark */
#include "base16-charcoal-dark.h" /* dark */
#include "base16-charcoal-light.h" /* light */
#include "base16-chicago-day.h" /* light */
#include "base16-chicago-night.h" /* dark */
#include "base16-chinoiserie-midnight.h" /* dark */
#include "base16-chinoiserie-morandi.h" /* dark */
#include "base16-chinoiserie-night.h" /* dark */
#include "base16-chinoiserie.h" /* light */
#include "base16-circus.h" /* dark */
#include "base16-classic-dark.h" /* dark */
#include "base16-classic-light.h" /* light */
#include "base16-codeschool.h" /* dark */
#include "base16-colors.h" /* dark */
#include "base16-corduroy-dark.h" /* dark */
#include "base16-corduroy.h" /* dark */
#include "base16-cupcake.h" /* light */
#include "base16-cupertino.h" /* light */
#include "base16-cyberpunk.h" /* dark */
#include "base16-da-one-black.h" /* dark */
#include "base16-da-one-gray.h" /* dark */
#include "base16-da-one-ocean.h" /* dark */
#include "base16-da-one-paper.h" /* light */
#include "base16-da-one-sea.h" /* dark */
#include "base16-da-one-white.h" /* light */
#include "base16-danqing-light.h" /* light */
#include "base16-danqing.h" /* dark */
#include "base16-darcula.h" /* dark */
#include "base16-darkmoss.h" /* dark */
#include "base16-darktooth.h" /* dark */
#include "base16-darkviolet.h" /* dark */
#include "base16-decaf.h" /* dark */
#include "base16-deep-oceanic-next.h" /* dark */
#include "base16-default-dark.h" /* dark */
#include "base16-default-light.h" /* light */
#include "base16-digital-rain.h" /* dark */
#include "base16-dirtysea.h" /* light */
#include "base16-dracula.h" /* dark */
#include "base16-edge-dark.h" /* dark */
#include "base16-edge-light.h" /* light */
#include "base16-eighties.h" /* dark */
#include "base16-eldritch.h" /* dark */
#include "base16-embers-light.h" /* light */
#include "base16-embers.h" /* dark */
#include "base16-emil.h" /* light */
#include "base16-equilibrium-dark.h" /* dark */
#include "base16-equilibrium-gray-dark.h" /* dark */
#include "base16-equilibrium-gray-light.h" /* light */
#include "base16-equilibrium-light.h" /* light */
#include "base16-eris.h" /* dark */
#include "base16-espresso.h" /* dark */
#include "base16-eva-dim.h" /* dark */
#include "base16-eva.h" /* dark */
#include "base16-evenok-dark.h" /* dark */
#include "base16-everforest-dark-hard.h" /* dark */
#include "base16-everforest-dark-medium.h" /* dark */
#include "base16-everforest-dark-soft.h" /* dark */
#include "base16-everforest-light-hard.h" /* light */
#include "base16-everforest-light-medium.h" /* light */
#include "base16-everforest-light-soft.h" /* light */
#include "base16-everforest.h" /* dark */
#include "base16-flat.h" /* dark */
#include "base16-flexoki-dark.h" /* dark */
#include "base16-flexoki-light.h" /* light */
#include "base16-framer.h" /* dark */
#include "base16-fruit-soda.h" /* light */
#include "base16-gigavolt.h" /* dark */
#include "base16-github-dark-colorblind.h" /* dark */
#include "base16-github-dark-dimmed.h" /* dark */
#include "base16-github-dark-high-contrast.h" /* dark */
#include "base16-github-dark.h" /* dark */
#include "base16-github-light-colorblind.h" /* light */
#include "base16-github-light-high-contrast.h" /* light */
#include "base16-github.h" /* light */
#include "base16-google-dark.h" /* dark */
#include "base16-google-light.h" /* light */
#include "base16-gotham.h" /* dark */
#include "base16-grayscale-dark.h" /* dark */
#include "base16-grayscale-light.h" /* light */
#include "base16-greenscreen.h" /* dark */
#include "base16-gruber.h" /* dark */
#include "base16-gruvbox-dark-hard.h" /* dark */
#include "base16-gruvbox-dark-medium-forest.h" /* dark */
#include "base16-gruvbox-dark-medium.h" /* dark */
#include "base16-gruvbox-dark-pale.h" /* dark */
#include "base16-gruvbox-dark-soft.h" /* dark */
#include "base16-gruvbox-dark.h" /* dark */
#include "base16-gruvbox-light-hard.h" /* light */
#include "base16-gruvbox-light-medium.h" /* light */
#include "base16-gruvbox-light-soft.h" /* light */
#include "base16-gruvbox-light.h" /* light */
#include "base16-gruvbox-material-dark-hard.h" /* dark */
#include "base16-gruvbox-material-dark-medium.h" /* dark */
#include "base16-gruvbox-material-dark-soft.h" /* dark */
#include "base16-gruvbox-material-light-hard.h" /* light */
#include "base16-gruvbox-material-light-medium.h" /* light */
#include "base16-gruvbox-material-light-soft.h" /* light */
#include "base16-hardcore.h" /* dark */
#include "base16-hardhacker.h" /* dark */
#include "base16-harmonic16-dark.h" /* dark */
#include "base16-harmonic16-light.h" /* light */
#include "base16-heetch-light.h" /* light */
#include "base16-heetch.h" /* dark */
#include "base16-helios.h" /* dark */
#include "base16-hopscotch.h" /* dark */
#include "base16-horizon-dark.h" /* dark */
#include "base16-horizon-light.h" /* light */
#include "base16-horizon-terminal-dark.h" /* dark */
#include "base16-horizon-terminal-light.h" /* light */
#include "base16-humanoid-dark.h" /* dark */
#include "base16-humanoid-light.h" /* light */
#include "base16-ia-dark.h" /* dark */
#include "base16-ia-light.h" /* light */
#include "base16-icy.h" /* dark */
#include "base16-irblack.h" /* dark */
#include "base16-isotope.h" /* dark */
#include "base16-jabuti.h" /* dark */
#include "base16-jellybeans.h" /* dark */
#include "base16-kanagawa-dragon.h" /* dark */
#include "base16-kanagawa.h" /* dark */
#include "base16-katy.h" /* dark */
#include "base16-kimber.h" /* dark */
#include "base16-kissa-latte.h" /* light */
#include "base16-kissa-macchiato.h" /* dark */
#include "base16-lichen-chartreuse-dark.h" /* dark */
#include "base16-lichen-chartreuse-light.h" /* light */
#include "base16-lime.h" /* dark */
#include "base16-linux-vt.h" /* dark */
#include "base16-macintosh.h" /* dark */
#include "base16-marrakesh.h" /* dark */
#include "base16-materia.h" /* dark */
#include "base16-material-darker.h" /* dark */
#include "base16-material-lighter.h" /* light */
#include "base16-material-palenight.h" /* dark */
#include "base16-material-vivid.h" /* dark */
#include "base16-material.h" /* dark */
#include "base16-measured-dark.h" /* dark */
#include "base16-measured-light.h" /* light */
#include "base16-mellow-purple.h" /* dark */
#include "base16-mexico-light.h" /* light */
#include "base16-mezcal.h" /* dark */
#include "base16-mocha.h" /* dark */
#include "base16-monokai.h" /* dark */
#include "base16-moonlight.h" /* dark */
#include "base16-mountain.h" /* dark */
#include "base16-nebula.h" /* dark */
#include "base16-neovim-dark.h" /* dark */
#include "base16-neovim-light.h" /* light */
#include "base16-noche.h" /* dark */
#include "base16-nord-light.h" /* light */
#include "base16-nord.h" /* dark */
#include "base16-nova.h" /* dark */
#include "base16-ocean.h" /* dark */
#include "base16-oceanicnext.h" /* dark */
#include "base16-ocote.h" /* dark */
#include "base16-one-light.h" /* light */
#include "base16-onedark-dark.h" /* dark */
#include "base16-onedark.h" /* dark */
#include "base16-outrun-dark.h" /* dark */
#include "base16-oxocarbon-dark.h" /* dark */
#include "base16-oxocarbon-light.h" /* light */
#include "base16-pandora.h" /* dark */
#include "base16-papel.h" /* light */
#include "base16-papercolor-dark.h" /* dark */
#include "base16-papercolor-light.h" /* light */
#include "base16-paraiso.h" /* dark */
#include "base16-pasque.h" /* dark */
#include "base16-pastelon-de-amarillos-dark.h" /* dark */
#include "base16-pastelon-de-amarillos.h" /* light */
#include "base16-penumbra-dark-contrast-plus-plus.h" /* dark */
#include "base16-penumbra-dark-contrast-plus.h" /* dark */
#include "base16-penumbra-dark.h" /* dark */
#include "base16-penumbra-light-contrast-plus-plus.h" /* light */
#include "base16-penumbra-light-contrast-plus.h" /* light */
#include "base16-penumbra-light.h" /* light */
#include "base16-phd.h" /* dark */
#include "base16-pico.h" /* dark */
#include "base16-pinky.h" /* dark */
#include "base16-pop.h" /* dark */
#include "base16-porple.h" /* dark */
#include "base16-precious-dark-eleven.h" /* dark */
#include "base16-precious-dark-fifteen.h" /* dark */
#include "base16-precious-light-warm.h" /* light */
#include "base16-precious-light-white.h" /* light */
#include "base16-primer-dark-dimmed.h" /* dark */
#include "base16-primer-dark.h" /* dark */
#include "base16-primer-light.h" /* light */
#include "base16-purpledream.h" /* dark */
#include "base16-qualia.h" /* dark */
#include "base16-railscasts.h" /* dark */
#include "base16-rebecca.h" /* dark */
#include "base16-rose-pine-dawn.h" /* light */
#include "base16-rose-pine-moon.h" /* dark */
#include "base16-rose-pine.h" /* dark */
#include "base16-saga.h" /* dark */
#include "base16-sagelight.h" /* light */
#include "base16-sakura.h" /* light */
#include "base16-sandcastle.h" /* dark */
#include "base16-selenized-black.h" /* dark */
#include "base16-selenized-dark.h" /* dark */
#include "base16-selenized-light.h" /* light */
#include "base16-selenized-white.h" /* light */
#include "base16-seti.h" /* dark */
#include "base16-shades-of-purple.h" /* dark */
#include "base16-shadesmear-dark.h" /* dark */
#include "base16-shadesmear-light.h" /* light */
#include "base16-shapeshifter.h" /* light */
#include "base16-silk-dark.h" /* dark */
#include "base16-silk-light.h" /* light */
#include "base16-snazzy.h" /* dark */
#include "base16-soft-server.h" /* dark */
#include "base16-solarflare-light.h" /* light */
#include "base16-solarflare.h" /* dark */
#include "base16-solarized-dark.h" /* dark */
#include "base16-solarized-light.h" /* light */
#include "base16-spaceduck.h" /* dark */
#include "base16-spacemacs.h" /* dark */
#include "base16-sparky.h" /* dark */
#include "base16-standardized-dark.h" /* dark */
#include "base16-standardized-light.h" /* light */
#include "base16-stella.h" /* dark */
#include "base16-still-alive.h" /* light */
#include "base16-summercamp.h" /* dark */
#include "base16-summerfruit-dark.h" /* dark */
#include "base16-summerfruit-light.h" /* light */
#include "base16-swamp-dark.h" /* dark */
#include "base16-swamp-light.h" /* light */
#include "base16-synth-midnight-dark.h" /* dark */
#include "base16-synth-midnight-light.h" /* light */
#include "base16-tango.h" /* dark */
#include "base16-tarot.h" /* dark */
#include "base16-tender.h" /* dark */
#include "base16-terracotta-dark.h" /* dark */
#include "base16-terracotta.h" /* light */
#include "base16-tinta.h" /* dark */
#include "base16-tokyo-city-dark.h" /* dark */
#include "base16-tokyo-city-light.h" /* light */
#include "base16-tokyo-city-terminal-dark.h" /* dark */
#include "base16-tokyo-city-terminal-light.h" /* light */
#include "base16-tokyo-night-dark.h" /* dark */
#include "base16-tokyo-night-light.h" /* light */
#include "base16-tokyo-night-moon.h" /* dark */
#include "base16-tokyo-night-storm.h" /* dark */
#include "base16-tokyo-night-terminal-dark.h" /* dark */
#include "base16-tokyo-night-terminal-light.h" /* light */
#include "base16-tokyo-night-terminal-storm.h" /* dark */
#include "base16-tokyodark-terminal.h" /* dark */
#include "base16-tokyodark.h" /* dark */
#include "base16-tomorrow-night-eighties.h" /* dark */
#include "base16-tomorrow-night.h" /* dark */
#include "base16-tomorrow.h" /* light */
#include "base16-tube.h" /* dark */
#include "base16-twilight.h" /* dark */
#include "base16-unikitty-dark.h" /* dark */
#include "base16-unikitty-light.h" /* light */
#include "base16-unikitty-reversible.h" /* dark */
#include "base16-uwunicorn.h" /* dark */
#include "base16-valua.h" /* dark */
#include "base16-vesper.h" /* dark */
#include "base16-vice.h" /* dark */
#include "base16-vulcan.h" /* dark */
#include "base16-windows-10-light.h" /* light */
#include "base16-windows-10.h" /* dark */
#include "base16-windows-95-light.h" /* light */
#include "base16-windows-95.h" /* dark */
#include "base16-windows-highcontrast-light.h" /* light */
#include "base16-windows-highcontrast.h" /* dark */
#include "base16-windows-nt-light.h" /* light */
#include "base16-windows-nt.h" /* dark */
#include "base16-woodland.h" /* dark */
#include "base16-xcode-dusk.h" /* dark */
#include "base16-yesterday-bright.h" /* dark */
#include "base16-yesterday-night.h" /* dark */
#include "base16-yesterday.h" /* dark */
#include "base16-zenbones.h" /* dark */
#include "base16-zenburn.h" /* dark */
#include "base24-0x96f.h" /* dark */
#include "base24-3024-day.h" /* light */
#include "base24-3024-night.h" /* dark */
#include "base24-adventure-time.h" /* dark */
#include "base24-alien-blood.h" /* dark */
#include "base24-alucard.h" /* light */
#include "base24-apprentice.h" /* dark */
#include "base24-argonaut.h" /* dark */
#include "base24-arthur.h" /* dark */
#include "base24-atelier-sulphurpool.h" /* dark */
#include "base24-ayu-dark.h" /* dark */
#include "base24-ayu-light.h" /* light */
#include "base24-ayu-mirage.h" /* dark */
#include "base24-banana-blueberry.h" /* dark */
#include "base24-batman.h" /* dark */
#include "base24-birds-of-paradise.h" /* dark */
#include "base24-blazer.h" /* dark */
#include "base24-blue-berry-pie.h" /* dark */
#include "base24-blue-matrix.h" /* dark */
#include "base24-bluloco-dark.h" /* dark */
#include "base24-bluloco-light.h" /* light */
#include "base24-borland.h" /* dark */
#include "base24-breeze.h" /* dark */
#include "base24-broadcast.h" /* dark */
#include "base24-brogrammer.h" /* dark */
#include "base24-builtin-dark.h" /* dark */
#include "base24-builtin-light.h" /* light */
#include "base24-builtin-pastel-dark.h" /* dark */
#include "base24-builtin-solarized-dark.h" /* dark */
#include "base24-builtin-solarized-light.h" /* light */
#include "base24-builtin-tango-dark.h" /* dark */
#include "base24-builtin-tango-light.h" /* light */
#include "base24-catppuccin-frappe.h" /* dark */
#include "base24-catppuccin-latte.h" /* light */
#include "base24-catppuccin-macchiato.h" /* dark */
#include "base24-catppuccin-mocha.h" /* dark */
#include "base24-cerulean-signal-dark.h" /* dark */
#include "base24-cerulean-signal-light.h" /* light */
#include "base24-chalk.h" /* dark */
#include "base24-chalkboard.h" /* dark */
#include "base24-challenger-deep.h" /* dark */
#include "base24-ciapre.h" /* dark */
#include "base24-clrs.h" /* light */
#include "base24-cobalt-neon.h" /* dark */
#include "base24-cobalt2.h" /* dark */
#include "base24-crayon-pony-fish.h" /* dark */
#include "base24-cyberdyne.h" /* dark */
#include "base24-dark-plus.h" /* dark */
#include "base24-deep-oceanic-next.h" /* dark */
#include "base24-deep.h" /* dark */
#include "base24-desert.h" /* dark */
#include "base24-dimmed-monokai.h" /* dark */
#include "base24-dracula.h" /* dark */
#include "base24-earthsong.h" /* dark */
#include "base24-eldritch.h" /* dark */
#include "base24-elemental.h" /* dark */
#include "base24-elementary.h" /* dark */
#include "base24-embarcadero.h" /* dark */
#include "base24-encom.h" /* dark */
#include "base24-espresso-libre.h" /* dark */
#include "base24-espresso.h" /* dark */
#include "base24-fideloper.h" /* dark */
#include "base24-firefox-dev.h" /* dark */
#include "base24-fish-tank.h" /* dark */
#include "base24-flat.h" /* dark */
#include "base24-flatland.h" /* dark */
#include "base24-flexoki-dark.h" /* dark */
#include "base24-flexoki-light.h" /* light */
#include "base24-floraverse.h" /* dark */
#include "base24-forest-blue.h" /* dark */
#include "base24-framer.h" /* dark */
#include "base24-front-end-delight.h" /* dark */
#include "base24-fun-forrest.h" /* dark */
#include "base24-galaxy.h" /* dark */
#include "base24-github-dark-colorblind.h" /* dark */
#include "base24-github-dark-dimmed.h" /* dark */
#include "base24-github-dark-high-contrast.h" /* dark */
#include "base24-github-dark.h" /* dark */
#include "base24-github-light-colorblind.h" /* light */
#include "base24-github-light-high-contrast.h" /* light */
#include "base24-github-light.h" /* light */
#include "base24-grape.h" /* dark */
#include "base24-gruvbox-dark.h" /* dark */
#include "base24-gruvbox-light.h" /* light */
#include "base24-hacktober.h" /* dark */
#include "base24-hardcore.h" /* dark */
#include "base24-highway.h" /* dark */
#include "base24-hipster-green.h" /* dark */
#include "base24-hivacruz.h" /* dark */
#include "base24-homebrew.h" /* dark */
#include "base24-hopscotch.h" /* dark */
#include "base24-hurtado.h" /* dark */
#include "base24-hybrid.h" /* dark */
#include "base24-ic-green-ppl.h" /* dark */
#include "base24-ic-orange-ppl.h" /* dark */
#include "base24-idea.h" /* dark */
#include "base24-idle-toes.h" /* dark */
#include "base24-jackie-brown.h" /* dark */
#include "base24-japanesque.h" /* dark */
#include "base24-jellybeans.h" /* dark */
#include "base24-jet-brains-darcula.h" /* dark */
#include "base24-kanagawa-dragon.h" /* dark */
#include "base24-kibble.h" /* dark */
#include "base24-lab-fox.h" /* dark */
#include "base24-laser.h" /* dark */
#include "base24-later-this-evening.h" /* dark */
#include "base24-lavandula.h" /* dark */
#include "base24-lichen-chartreuse-dark.h" /* dark */
#include "base24-lichen-chartreuse-light.h" /* light */
#include "base24-lovelace.h" /* dark */
#include "base24-man-page.h" /* light */
#include "base24-material-dark.h" /* dark */
#include "base24-material.h" /* light */
#include "base24-mathias.h" /* dark */
#include "base24-medallion.h" /* dark */
#include "base24-mission-brogue.h" /* dark */
#include "base24-misterioso.h" /* dark */
#include "base24-molokai.h" /* dark */
#include "base24-mona-lisa.h" /* dark */
#include "base24-monokai-vivid.h" /* dark */
#include "base24-mountain.h" /* dark */
#include "base24-night-lion-v1.h" /* dark */
#include "base24-night-lion-v2.h" /* dark */
#include "base24-night-owlish-light.h" /* light */
#include "base24-nocturnal-winter.h" /* dark */
#include "base24-obsidian.h" /* dark */
#include "base24-ocean.h" /* dark */
#include "base24-oceanic-material.h" /* dark */
#include "base24-ollie.h" /* dark */
#include "base24-one-black.h" /* dark */
#include "base24-one-dark.h" /* dark */
#include "base24-one-half-light.h" /* dark */
#include "base24-one-light.h" /* light */
#include "base24-operator-mono-dark.h" /* dark */
#include "base24-pandora.h" /* dark */
#include "base24-papercolor-dark.h" /* dark */
#include "base24-papercolor-light.h" /* light */
#include "base24-pastelon-de-amarillos-dark.h" /* dark */
#include "base24-pastelon-de-amarillos.h" /* light */
#include "base24-paul-millr.h" /* dark */
#include "base24-pencil-dark.h" /* dark */
#include "base24-pencil-light.h" /* light */
#include "base24-piatto-light.h" /* light */
#include "base24-pnevma.h" /* dark */
#include "base24-pro-light.h" /* light */
#include "base24-pro.h" /* dark */
#include "base24-purple-rain.h" /* dark */
#include "base24-purplepeter.h" /* dark */
#include "base24-rebecca.h" /* dark */
#include "base24-red-alert.h" /* dark */
#include "base24-red-planet.h" /* dark */
#include "base24-red-sands.h" /* dark */
#include "base24-rippedcasts.h" /* dark */
#include "base24-royal.h" /* dark */
#include "base24-scarlet-protocol.h" /* dark */
#include "base24-sea-shells.h" /* dark */
#include "base24-seafoam-pastel.h" /* dark */
#include "base24-shades-of-purple.h" /* dark */
#include "base24-shaman.h" /* dark */
#include "base24-slate.h" /* dark */
#include "base24-sleepy-hollow.h" /* dark */
#include "base24-smyck.h" /* dark */
#include "base24-solarized-dark-higher-contrast.h" /* dark */
#include "base24-solarized-dark-patched.h" /* dark */
#include "base24-space-gray-eighties-dull.h" /* dark */
#include "base24-space-gray-eighties.h" /* dark */
#include "base24-spacedust.h" /* dark */
#include "base24-sparky.h" /* dark */
#include "base24-spiderman.h" /* dark */
#include "base24-square.h" /* dark */
#include "base24-sundried.h" /* dark */
#include "base24-tango-adapted.h" /* light */
#include "base24-tango-half-adapted.h" /* light */
#include "base24-terminal-basic.h" /* light */
#include "base24-thayer-bright.h" /* dark */
#include "base24-the-hulk.h" /* dark */
#include "base24-tokyo-night-dark.h" /* dark */
#include "base24-tokyo-night-light.h" /* light */
#include "base24-tokyo-night-moon.h" /* dark */
#include "base24-tokyo-night-storm.h" /* dark */
#include "base24-tomorrow-night.h" /* dark */
#include "base24-toy-chest.h" /* dark */
#include "base24-treehouse.h" /* dark */
#include "base24-twilight.h" /* dark */
#include "base24-ubuntu.h" /* dark */
#include "base24-ultra-violet.h" /* dark */
#include "base24-under-the-sea.h" /* dark */
#include "base24-unikitty.h" /* light */
#include "base24-vibrant-ink.h" /* dark */
#include "base24-violet-dark.h" /* dark */
#include "base24-violet-light.h" /* light */
#include "base24-warm-neon.h" /* dark */
#include "base24-wez.h" /* dark */
#include "base24-wild-cherry.h" /* dark */
#include "base24-wombat.h" /* dark */
#include "base24-wryan.h" /* dark */
#include "base24-zenburn.h" /* dark */

#endif /* TINTED_C_H__ */
